### ISSUE TITLE
Moving to Operator SDK

### ISSUE THREAD

**Issue by leelavg** [alauda/nativestor#86]
@little-guy-lxr 

- Can you please create a new branch for operator-sdk
- I'll send commits to that from time to time and when it's suitable with current functionality we can change the branches?
- Do you still wish to support `api/v1`?

I don't have triage rights, pls assign this issue to me.

**Comment by little-guy-lxr** [comment]
@leelavg  I have add triage rights  for you.  
branch operator-sdk-dev has been created.

**Comment by leelavg** [comment]
- how are you including topolvm crd as well in the csv?

**Comment by leelavg** [comment]
- btw, work upto now can be tracked in https://github.com/leelavg/top-sdk once e2e passes I'll squash all that to a single commit and rebase on current `main` and push to `operator-sdk-dev`

**Comment by little-guy-lxr** [comment]
> * how are you including topolvm crd as well in the csv?

@leelavg add that manually.
